### ISSUE TITLE
Keep slot signals in the same bank

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#11]
If that's not possible then keep clock capable signals with the same byte (so lvds0 and lvds1-7 in the same bank and lvds8 and lvds 9-15 in the same bank).

**Comment by filipswit** [comment]
Can you point which exactly are wrongly connected?

**Comment by marmeladapk** [comment]
On a closer look I didn't find any problems. I must have misread signal names in bank 2.
