### ISSUE TITLE
Check impedance rules

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#12]
Some differential pairs are assigned to D100 net class, some are assigned to Diff_100Ohm differential net class (via differential pair directive).

Moreover in PCB rules 100 Ohm rule is assigned to all differential pairs and takes precedence over 90 Ohm rule (causing usb to be routed as 100 Ohm).

Please switch to a single net class assignment type (either net class or differential net class). Personally I'd prefer to use differential net classes, as they can be assigned in differential routing rules without using custom queries and it logically separates differential pair and SE signals. Differential directive can also be applied to a directive blanket (this may help to declutter schematics btw).

![obraz](https://github.com/sinara-hw/KASLI-DIOT/assets/24512604/8bd7f437-b14d-4801-90d1-29ff1d821913)

**Comment by filipswit** [comment]
Fixed.
