### ISSUE TITLE
LVCMOS input can't be AC coupled for Si53312

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#17]
Also DNP R12 in CMOS variant

Datasheet says that for LVCMOS source and sink vdd should be equal. We have P2V5 for source and P3V3 for sink. But we still clear the bar for V_ih in single ended mode.

**Comment by filipswit** [comment]
Do we actually need CMOS variant? I don't think we have ever used CMOS oscillators

**Comment by gkasprow** [comment]
No. Just one single variant

Pozdrawiam / Best regards
G.Kasprowicz
________________________________

**Comment by filipswit** [comment]
It's not valid since we leave one single variant.
