### ISSUE TITLE
SCH and PCB review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/KASLI-DIOT#2]
- [x] Move the bootloader button closer to the edge
- [x] Mark 12V connector as DNP or move it to the back - now it obstructs the airflow
- [x] Route I2C to the mezzanine in case we want to add additional SFPs

**Comment by filipswit** [comment]
> Move the bootloader button closer to the edge

I don't think we can move it closer. It can't fit under the panel. We can optionally move it on TOP.


> Mark 12V connector as DNP or move it to the back - now it obstructs the airflow

We can try to move it to the right. For the first proto it will be needed to work on the table, later might be unmounted.
![image](https://github.com/sinara-hw/KASLI-DIOT/assets/24258965/e243b321-9f5c-4527-879f-8b29b5dab8bf)

**Comment by gkasprow** [comment]
Nie musisz odrazu pprawiac issues. Pawel bedzie robil review i pewnie i tak
cos wyjdzie.

niedz., 24 mar 2024, 20:45 użytkownik filipswit ***@***.***>
napisał:

**Comment by filipswit** [comment]
12V Connector moved, in future can be marked as DNP
![image](https://github.com/user-attachments/assets/25d8b4f0-f006-4db2-96ae-33810d7d4d5c)
