### ISSUE TITLE
Via connection

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#39]
![image](https://github.com/sinara-hw/KASLI-DIOT/assets/24512604/2c314408-dcac-4ebf-9830-71c223010953)

This via is not connected to P3V3.

**Comment by marmeladapk** [comment]
![Uploading image.png…]()

And these are not connected to P1V5.

**Comment by filipswit** [comment]
- P3V3 via has connection on bottom, we can't move this plane becaus it is reference for DDR. 
- P1V5 fixed
