### ISSUE TITLE
Add a buffer to clock input

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#4]
Then in case of an overdrive the buffer will fail, not the FPGA.

Similar thing should be done on Kasli and Kasli SoC as well IMO.

**Comment by gkasprow** [comment]
we can also use anti-parallel diodes like it's done in WR switch

**Comment by filipswit** [comment]
How about placing FIN1101?
![image](https://github.com/user-attachments/assets/dbe0e24c-1d43-4250-9504-58515e976cb4)

**Comment by jordens** [comment]
Is the performance of that buffer (phase noise, tempco, etc) known to be better than that of the FPGA?

**Comment by gkasprow** [comment]
Just add 2 diodes like bav99 as limiter

**Comment by filipswit** [comment]
ok, placed anti-parallel diodes BAV99 
![image](https://github.com/user-attachments/assets/58079514-bc09-41cf-8faf-139dde99efaa)
