### ISSUE TITLE
Reference plane change vias

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#40]
- [ ] Add via here:
![image](https://github.com/sinara-hw/KASLI-DIOT/assets/24512604/1fe56014-4bfc-47f3-a74d-fef4f87458bf)

In many places there's only one via for per differential pair when changing reference plane. Too many to list here.

- [ ] Add  capacitors here
![image](https://github.com/sinara-hw/KASLI-DIOT/assets/24512604/a7c18733-1a84-4f7d-8450-51b6bae2c9e1)

- Changes to/from layer 6 are problematic since there's a P3V3 plane closest but there are no capacitors fir this change (e.g. between layer 1 and layer 6 there should be a capacitor nearby from P2V5 to P3V3.)

**Comment by filipswit** [comment]
- Added vias whereber it was possible.
- Added capacitor.
- Made some changes in power planes, so now  L6 has P2V5 under
