### ISSUE TITLE
Floating net label GND is disconnected from set pin

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/KASLI-DIOT#7]
![obraz](https://github.com/sinara-hw/KASLI-DIOT/assets/24512604/33d48d23-af99-4aca-adb3-911294c22f18)

**Comment by marmeladapk** [comment]
BTW maybe move byte net class definitions to net labels connected to sdrams, that way you'll get rid of floating net label warnings in which this error was hidden.

**Comment by filipswit** [comment]
fixed
